### ISSUE TITLE
cannot find 'feature_names.json'

### ISSUE THREAD

**Issue by andy7002** [jyansir/tp-berta#2]
Hi, everyone:
I run project, cannot find 'feature_names.json' file.

D:\conda_env\py38_tpberta\python.exe E:\project\tp-berta\scripts\finetune\default\run_default_config_tree.py --task=regression 
load data config from: E:\project\tp-berta\scripts\finetune\default\checkpoints\tp-bin
Traceback (most recent call last):
  File "E:\project\tp-berta\scripts\finetune\default\run_default_config_tree.py", line 85, in <module>
    data_config = DataConfig.from_pretrained(
  File "E:\project\tp-berta\lib\data_utils.py", line 93, in from_pretrained
    return DataConfig.from_config(config, tokenizer)
  File "E:\project\tp-berta\lib\data_utils.py", line 116, in from_config
    with open(data_dir  /feature_map_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\project\\tp-berta\\scripts\\finetune\\default\\data\\finetune-reg\\feature_names.json'

**Comment by andy7002** [comment]
clean_feat_names.py gen it.
